# FILE: .github/workflows/seasonality_cron.yml
# --- Updated to install the yfinance library ---

name: Calculate Daily Seasonality

on:
  schedule:
    # Runs at 1 AM UTC every day (after market close)
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  calculate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Added 'yfinance' to the list of packages to install
          pip install requests pandas numpy yfinance

      - name: Run Seasonality Calculation Script
        run: python worker/calculate_seasonality.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/scan_results.json
          git diff --staged --quiet || git commit -m "Update daily seasonality scan results"
          git push
